### ISSUE TITLE
Coqtail will not start server

### ISSUE THREAD

**Issue by CTHULHU-Jesus** [whonore/Coqtail#239]
I get this error when I do CoqStart. I don't know why.

`Error detected while processing function coqtail#start[6]..coqtail#init[2]..provider#python3#Call:              
line   18:                                                                                                      
Error invoking 'python_eval' on channel 3 (python3-script-host):                                                
error caught in request handler 'python_eval ['CoqtailServer.start_server(bool(0))']':                          
Traceback (most recent call last):                                                                              
  File "/usr/local/lib/python3.8/dist-packages/pynvim/plugin/script_host.py", line 167, in python_eval          
    return eval(expr, self.module.__dict__)                                                                     
  File "<string>", line 1, in <module>                                                                          
  File "/home/haster/.vim/plugged/Coqtail/python/coqtail.py", line 949, in start_server                         
    CoqtailServer.serv = ThreadingTCPServer(("localhost", 0), CoqtailHandler)                                   
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__                                              
    self.server_bind()                                                                                          
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind                                           
    self.socket.bind(self.server_address)                                                                       
OSError: [Errno 99] Cannot assign requested address                                                             
Press ENTER or type command to continue`

My version of coq
`$coqtop --version
The Coq Proof Assistant, version 8.11.0 (March 2020)
compiled on Mar 5 2020 20:37:30 with OCaml 4.08.1
`

version of python= 3.8.10

**Comment by CTHULHU-Jesus** [comment]
I had the line `127.0.0.1 *.localhost` for a different project.
After adding the line `127.0.0.1 localhost` It works again. I was the problem.
