### ISSUE TITLE
Error after git pull: `No such highlight group name: CoqtailSent`

### ISSUE THREAD

**Issue by vsiles** [whonore/Coqtail#38]
Hi !
I updated my vim / plugins this morning and I got the following error message after my first evaluation command (leader c j, :CoqStart is fine):
```
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vsiles/.vim/bundle/Coqtail/python/coqtail.py", line 162, in step
    self.send_until_fail()
  File "/Users/vsiles/.vim/bundle/Coqtail/python/coqtail.py", line 276, in send_until_fail
    self.reset_color()
  File "/Users/vsiles/.vim/bundle/Coqtail/python/coqtail.py", line 612, in reset_color
    _make_matcher((sline, scol + 1), (eline + 1, ecol)),
  File "/Users/vsiles/.vim/bundle/Coqtail/python/coqtail.py", line 734, in matchadd
    vim.command("let b:{} = matchadd('{}', '{}')".format(var, group, zone))
vim.error: Vim(let):E28: No such highlight group name: CoqtailSent
```

Here are my revisions/versions:
- coqtail: 97d1633f01a48341d8668aa7d46f9d0295d631f8
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  3 2019 04:49:45)
macOS version
Included patches: 1-1450
Compiled by Homebrew
- The Coq Proof Assistant, version 8.8.0 (February 2019)
compiled on Feb 1 2019 10:31:25 with OCaml 4.07.0

**Comment by whonore** [comment]
Do you have `g:coqtail_nosyntax = 1`?

**Comment by vsiles** [comment]
No, I don't seem to have that variable set (`:let g:coqtail_<tab>` only returns coqtail_project_name and coqtail_sourced, and I don't have anything in my .vimrc).

**Comment by whonore** [comment]
Could you see if 0bf1da0 fixes the problem?

**Comment by vsiles** [comment]
I don't have the time to test it in deep atm but a rapid test says it is fixed ! Thank you. I'll try to test in more later next week.

**Comment by whonore** [comment]
Great, I'll leave this issue open for now in case you run into any more problems with this.

**Comment by vsiles** [comment]
No issue this morning, it seems to be correctly fixed. Again, thanks a lot !

**Comment by vsiles** [comment]
I just got the same kind of error message in a different scenario, with `CoqtailError`:
```
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vsiles/.vim/bundle/Coqtail/python/coqtail.py", line 162, in step
    self.send_until_fail()
  File "/Users/vsiles/.vim/bundle/Coqtail/python/coqtail.py", line 276, in send_until_fail
    self.reset_color()
  File "/Users/vsiles/.vim/bundle/Coqtail/python/coqtail.py", line 620, in reset_color
    _make_matcher((sline + 1, scol), (eline + 1, ecol)),
  File "/Users/vsiles/.vim/bundle/Coqtail/python/coqtail.py", line 734, in matchadd
    vim.command("let b:{} = matchadd('{}', '{}')".format(var, group, zone))
vim.error: Vim(let):E28: No such highlight group name: CoqtailError
```

**Comment by whonore** [comment]
I forgot to move `CoqtailError` highlighting with the other Coqtail groups. Should work now.

**Comment by vsiles** [comment]
I confirm that master is fixed, thank you !
