### ISSUE TITLE
Freeze on command and crash on CoqToggleDebug

### ISSUE THREAD

**Issue by joxcat** [whonore/Coqtail#68]
Hello ! I'm using Coqtail on manjaro with :
*nvim => 0.4.2 (`echo has("python3")` return 1)
vim-plug => latest version (by 11/2/2019)
coq => 8.8.2 (using opam 2.0.5)
python3 => 3.7.4 (with pynvim 0.3.2)
python2 => 2.7.17 (with pynvim 0.3.2)*

When I use `CoqStart` nvim freeze and to continue I must use `C-c-c`, then an error message display during a few milliseconds and then disappear. If I retry to do `CoqStart` it says that coq is running.

But when I use any other command nvim is freezing.

And `CoqToggleDebug` is displaying this error : 
```shell
Error detected while processing function <SNR>109_Py[3]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kuro/.config/nvim/plugged/coqtail/python/coqtail.py", line 724, in toggle_debu
g
    self.show_info(msg)
  File "/home/kuro/.config/nvim/plugged/coqtail/python/coqtail.py", line 636, in show_info
    self.restore_panel(self.panel("info"), self.info_msg)
  File "/home/kuro/.config/nvim/plugged/coqtail/python/coqtail.py", line 775, in panel
    return vim.buffers[vim.current.buffer.vars["coqtail_panel_bufs"][name]]
  File "/usr/lib/python3.7/site-packages/pynvim/api/common.py", line 88, in __getitem__
    return self._get(key)
  File "/usr/lib/python3.7/site-packages/pynvim/api/common.py", line 51, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in reques
t
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Key not found: coqtail_panel_bufs'
```

Do you have any idea on what can cause theses problems ?

Thanks

*(I'm linking the file in coq that I use to have this error. Sorry if the comments are in french)*
[example.v.txt](https://github.com/whonore/Coqtail/files/3800605/example.v.txt)

**Comment by whonore** [comment]
Hi, unfortunately the way I have things currently structured doesn't work with neovim because I modify Vim variables in Python from the non-main thread (see https://github.com/whonore/Coqtail/issues/13#issuecomment-457844087 for a similar issue). I have some ideas to fix it but it will require some fairly significant changes that I haven't had time for yet.
