### ISSUE TITLE
Python errors `'str' object has no attribute 'decode'`

### ISSUE THREAD

**Issue by Cypher1** [whonore/Coqtail#70]
CoqStart succeeds but CoqNext fails with 
```
Error detected while processing function <SNR>81_Py[3]..provider#python3#Call:                                                
line   18:                                                                                                                    
Error invoking 'python_execute' on channel 4 (python3-script-host):                                                           
Traceback (most recent call last):                                                                                            
  File "<string>", line 1, in <module>                                                                                        
  File "/home/cypher/.local/share/nvim/plugged/Coqtail/python/coqtail.py", line 183, in step                                  
    failed_at = self.send_until_fail()                                                                                        
  File "/home/cypher/.local/share/nvim/plugged/Coqtail/python/coqtail.py", line 327, in send_until_fail                       
    encoding=self.encoding,                                                                                                   
  File "/home/cypher/.local/share/nvim/plugged/Coqtail/python/coqtail.py", line 731, in encoding                              
    return vim.options["encoding"].decode("utf-8") or "utf-8"                                                                 
AttributeError: 'str' object has no attribute 'decode'
```

I've only recently updated all my packages on Manjaro and have run checkhealth with nothing suspicious. I've also only just installed Coqtail. CoqIDE is working fine for the same file so I don't think it's a back end failure.

Thanks in advance

**Comment by whonore** [comment]
Thanks for reporting. I guess in neovim `vim.options["encoding"]` is a `str` instead of `bytes` like in vim. It's actually interesting that you could even hit that error since most neovim users seem to encounter an error during `CoqStart` (#13 #68). If after fixing this bug Coqtail works for you I'd be interested to try to figure out what about your configuration lets you avoid that problem.

**Comment by Cypher1** [comment]
Thanks @whonore . Versions installed are as follows:
```
coqc: 8.10.1 compiled with ocaml: 4.09.0
nvim: 0.4.3 using LauJIT: 2.0.5
python: 3.7.4
linux: linux 5.4.0-1-MANJARO x86_64
```

Otherwise I don't think I have any particular set up.
